#!/bin/bash

alias ssb="source $HOME/.bashrc"

# sudo
alias sudo=/usr/bin/doas

# power
alias reboot="/usr/bin/doas /usr/bin/reboot"
alias poweroff="/usr/bin/doas /usr/bin/poweroff"

# xdg-mime
alias xxff="/usr/bin/xdg-mime query filetype"
alias xxqq="/usr/bin/xdg-mime query default"
alias xxd="/usr/bin/xdg-mime default"
alias xx="/usr/bin/xdg-open"
alias umd="/usr/bin/update-mime-database"

# desktop entries
alias dff="/usr/bin/desktop-file-validate"
alias ddi="/usr/bin/desktop-file-install"
alias udd="/usr/bin/update-desktop-database"

# xdg-dirs
#alias udu="/usr/bin/xdg-user-dirs-update"

# xrdb reload
alias xxx="/usr/bin/xrdb $XDG_CONFIG_HOME/X11/xresources"

# pacman
alias syu="/usr/bin/doas /usr/bin/pacman -Syu"
alias pis="/usr/bin/doas /usr/bin/pacman -S"
alias rns="/usr/bin/doas /usr/bin/pacman -Rns"
alias pss="/usr/bin/pacman -Ss"
alias psi="/usr/bin/pacman -Si"
alias pqs="/usr/bin/pacman -Qs"
alias pqe="/usr/bin/pacman -Qe"
alias pqi="/usr/bin/pacman -Qi"
alias Syu="/usr/bin/yay -Sua"
alias yss="/usr/bin/yay -Ss"
alias ysi="/usr/bin/yay -Si"
alias yqs="/usr/bin/yay -Qs"
alias yqe="/usr/bin/yay -Qe"
alias yqi="/usr/bin/yay -Qi"
alias yis="/usr/bin/yay -S"
# list all explicitely installed packages
alias pll="/usr/bin/pacman -Qe"

# journalctl
alias jctl="/usr/bin/journalctl -p 3 -xb" # show errors from journalctl

# gpg
alias gpg-check="/usr/bin/gpg2 --keyserver-options auto-key-retrieve --verify" # verify downloaded files
alias gpg-retrieve="/usr/bin/gpg2 --keyserver-options auto-key-retrieve --receive-keys" # receive keys of a developer

# pip
alias ppi="/usr/bin/pip install"
alias ppu="/usr/bin/pip uninstall"
alias ppl="/usr/bin/pip list"
alias ppc="/usr/bin/pip check"
alias pps="/usr/bin/pip show"

# git
alias status="/usr/bin/git status"
alias add="/usr/bin/git add"
alias remove="/usr/bin/git rm"
alias commit="/usr/bin/git commit -m"
alias push="/usr/bin/git push"
alias clone="/usr/bin/git clone"
alias pull="/usr/bin/git pull"

# navigation
alias ..="cd ..;/usr/bin/clear;/usr/bin/eza -lh --group-directories-first --grid"
alias ...="cd ../..;/usr/bin/clear;/usr/bin/eza -lh --group-directories-first --grid"
alias ....="cd ../../..;/usr/bin/clear;/usr/bin/eza -lh --group-directories-first --grid"
alias .....="cd ../../../..;/usr/bin/clear;/usr/bin/eza -lh --group-directories-first --grid"
alias ......="cd ../../../../..;/usr/bin/clear;/usr/bin/eza -lh --group-directories-first --grid"
alias ..t="cd ..;/usr/bin/clear;/usr/bin/tree -C"
alias ..tt="cd ..;/usr/bin/clear;/usr/bin/tree -d -C"
alias ...t="cd ../..;/usr/bin/clear;/usr/bin/tree -C"
alias ...tt="cd ../..;/usr/bin/clear;/usr/bin/tree -d -C"
alias ....t="cd ../../..;/usr/bin/clear;/usr/bin/tree -C"
alias ....tt="cd ../../..;/usr/bin/clear;/usr/bin/tree -d -C"
alias .....t="cd ../../../..;/usr/bin/clear;/usr/bin/tree -C"
alias .....tt="cd ../../../..;/usr/bin/clear;/usr/bin/tree -d -C"
alias ......t="cd ../../../../..;/usr/bin/clear;/usr/bin/tree -C"
alias ......tt="cd ../../../../..;/usr/bin/clear;/usr/bin/tree -d -C"

# cd
fcc() {
cd "$(/usr/bin/find $HOME -type d -path $HOME/vids -prune -false -o -type d -name '*' -print | /usr/bin/fzf)";/usr/bin/clear;/usr/bin/eza -lh --group-directories-first --grid
}
ftt() {
cd "$(/usr/bin/find $HOME -type d -path $HOME/vids -prune -false -o -type d -name '*' -print | /usr/bin/fzf)";/usr/bin/clear;/usr/bin/tree -aC
}
cdd() {
cd "$(/usr/bin/find . -type d | /usr/bin/fzf)";/usr/bin/clear;/usr/bin/eza -lh --group-directories-first --grid
}
ctt() {
cd "$(/usr/bin/find . -type d | /usr/bin/fzf)";/usr/bin/clear;/usr/bin/tree -aC
}

# grep
alias gss="/usr/bin/find $XDG_CONFIG_HOME/shell $HOME/.local/bin -type f -name '*' -print | /usr/bin/xargs /usr/bin/grep -iIn --color"
alias Gss="/usr/bin/find $XDG_CONFIG_HOME/shell $HOME/.local/bin -type f -name '*' -print | /usr/bin/xargs /usr/bin/grep -In --no-ignore-case --color"
alias gsss="/usr/bin/find $HOME/prog/suckless -type f -name '*' -print | /usr/bin/xargs /usr/bin/grep -iIn --color"
alias Gsss="/usr/bin/find $HOME/prog/suckless -type f -name '*' -print | /usr/bin/xargs /usr/bin/grep -In --no-ignore-case --color"

# clear
alias cl=/usr/bin/clear
alias clc="/usr/bin/clear;cd"
alias cll="/usr/bin/clear;/usr/bin/eza -lh --group-directories-first --grid"
alias clt="/usr/bin/clear;/usr/bin/tree -aC"
alias ct1="/usr/bin/clear;/usr/bin/tree -C -d -L 1"
alias ct2="/usr/bin/clear;/usr/bin/tree -C -d -L 2"
alias ct3="/usr/bin/clear;/usr/bin/tree -C -d -L 3"
alias ct4="/usr/bin/clear;/usr/bin/tree -C -d -L 4"

# tree
alias tree="/usr/bin/tree -aC"
alias tt1="/usr/bin/tree -C -d -L 1"
alias tt2="/usr/bin/tree -C -d -L 2"
alias tt3="/usr/bin/tree -C -d -L 3"
alias tt4="/usr/bin/tree -C -d -L 4"

# whereis
alias ww=/usr/bin/whereis

# checkbashisms
alias bism=/usr/bin/checkbashisms

# xdg-ninja
alias ninja="cd $HOME && /usr/bin/clear && /usr/bin/xdg-ninja"

# bulk rename
alias nn=/usr/bin/vimv
alias nnn="/usr/bin/doas /usr/bin/vimv"

# glow
alias gg="/usr/bin/glow -p"

# confirm before overwriting something
alias cp="/usr/bin/cp -vi"
alias ccp="/usr/bin/doas /usr/bin/cp -vi"
alias mv="/usr/bin/mv -vi"
alias mmv="/usr/bin/doas /usr/bin/mv -vi"
alias rm="/usr/bin/rm -vI"
alias rrm="/usr/bin/doas /usr/bin/rm -vI"
alias mkd="/usr/bin/mkdir -vp"
alias mmkd="/usr/bin/doas /usr/bin/mkdir -vp"

# chown
alias tt=/usr/bin/touch
alias modx="/usr/bin/chmod +x"
alias modu="/usr/bin/chmod -x"
alias own="/usr/bin/doas /usr/bin/chown -R $(/usr/bin/echo $(/usr/bin/id -un):$(/usr/bin/id -gn))"

# ls
alias ls="/usr/bin/eza -lh --group-directories-first --grid"
alias lsa="/usr/bin/eza -alh --group-directories-first --grid"
alias cc="/usr/bin/ls -A | /usr/bin/wc -l"

# rust alternatives
alias cat=/usr/bin/bat
alias rg="/usr/bin/rg -i --colors 'match:fg:green'"
alias fd="/usr/bin/fd -H -c auto" # search hidden files

# make
alias mmi="/usr/bin/doas /usr/bin/make clean install"
alias mmu="/usr/bin/doas /usr/bin/make clean uninstall"

# kill
alias kill="/usr/bin/kill -9"

## trash
#alias rmp="/usr/bin/trash put"
#alias rml="/usr/bin/trash list"
#alias rme="/usr/bin/trash empty"
#alias rmt="/usr/bin/trash restore"

## newsboat
#alias news="/usr/bin/newsboat -x reload"

# nsxiv
alias pp=/usr/bin/nsxiv

# mpv
alias mmm="/usr/bin/mpv *.mp4 *.mkv *.m4v"
alias mm=/usr/bin/mpv

# thumbnailer
alias txx="/usr/bin/vcs -i 1m -c 4"

# nvim
alias vi="/usr/bin/nvim -i NONE"
alias vim=/usr/bin/vi
alias svim="/usr/bin/doas /usr/bin/nvim"
alias vdiff="/usr/bin/nvim -d"
alias vimdiff="/usr/bin/nvim -d"

# ping
alias ping="/usr/bin/ping 8.8.8.8 -c 5"

# space
alias df="/usr/bin/df -h"
alias du=/usr/bin/ncdu
alias freemem="/usr/bin/free -h -s 1 -c 3"

# ytdl
alias yt="/usr/bin/yt-dlp -ic"
alias yta="/usr/bin/yt-dlp -xic"
alias qq="/usr/bin/torsocks /usr/bin/yt-dlp -ic"

# zathura
alias zz=/usr/bin/zathura

# torrent
alias torr=/usr/bin/attractorr

# libg
alias booka="cd $XDG_DOWNLOAD_DIR/libg && $HOME/.local/bin/libg -b author"
alias bookt="cd $XDG_DOWNLOAD_DIR/libg && $HOME/.local/bin/libg -b title"

# curl
alias ccc="/usr/bin/curl --remote-name"

# wget
alias wget="/usr/bin/wget --hsts-file=$XDG_DATA_HOME/wget-hsts"

# weather
alias wttr="/usr/bin/curl wttr.in/$place"

# surfraw
alias sr="/usr/bin/sr duckduckgo"

# w3m
alias www="/usr/bin/w3m -config $XDG_CONFIG_HOME/w3m/config"

# mail
alias mail="/usr/bin/mbsync -a -c $XDG_CONFIG_HOME/isync/mbsyncrc && /usr/bin/neomutt"

# abook
alias abook="/usr/bin/abook --config $XDG_CONFIG_HOME/abook/abookrc --datafile $XDG_DATA_HOME/abook/addressbook"

# mbsync
alias mbsync="/usr/bin/mbsync -c $XDG_CONFIG_HOME/isync/mbsyncrc"
alias sync="/usr/bin/mbsync -a -c $XDG_CONFIG_HOME/isync/mbsyncrc"

# checkupdates
alias cu="/usr/bin/pacman -Qu"
alias cn="/usr/bin/pacman -Qu | /usr/bin/wc -l"
alias Cu="/usr/bin/yay -Qu"
alias Cn="/usr/bin/yay -Qu | /usr/bin/wc -l"

# scim
alias sc=/usr/bin/sc-im

# mocp
alias moc="/usr/bin/mocp -M $XDG_CONFIG_HOME/moc"

# neofetch
alias fetch="$HOME/.local/bin/paleofetch"

# cron
alias cronl="/usr/bin/crontab -l"
alias crone="/usr/bin/crontab -e"

# network status
alias wifi="/usr/bin/iwctl station wlan0 show"
alias scan="/usr/bin/iwctl station wlan0 scan"
alias netw="/usr/bin/iwctl station wlan0 get-networks"

# mount
alias bbm="/usr/bin/doas /usr/bin/mount /dev/sdb1 /mnt/usb1 && cd /mnt/usb1 && /usr/bin/eza -alh --group-directories-first --grid"
alias ccm="/usr/bin/doas /usr/bin/mount /dev/sdc1 /mnt/usb2 && cd /mnt/usb2 && /usr/bin/eza -alh --group-directories-first --grid"
alias ddm="/usr/bin/doas /usr/bin/mount /dev/sdd1 /mnt/usb3 && cd /mnt/usb3 && /usr/bin/eza -alh --group-directories-first --grid"
alias bbu="cd && /usr/bin/doas /usr/bin/umount /dev/sdb1"
alias ccu="cd && /usr/bin/doas /usr/bin/umount /dev/sdc1"
alias ddu="cd && /usr/bin/doas /usr/bin/umount /dev/sdd1"

# latex
alias ll=/usr/bin/pdflatex

# when & task
alias cal="/usr/bin/cal -y"
alias calm="/usr/bin/when m"
alias caly="/usr/bin/when y"
alias cale="/usr/bin/when e"
alias todo=/usr/bin/task
alias ttt=/usr/bin/task
alias ttta="/usr/bin/task add"
alias ttte="/usr/bin/task edit"
alias tttu="/usr/bin/task undo"

# studyflash
alias sffn="/usr/bin/studyflash new"
alias sffa="/usr/bin/studyflash add"
alias sffe="/usr/bin/studyflash edit"
alias sffs="/usr/bin/studyflash study"

# adb
alias adb='HOME="$XDG_DATA_HOME"/android adb'

# sl
alias ctl=/usr/bin/sl

# sound by pamixer
alias mute="/usr/bin/pamixer -t"

# random identity generator
alias name=/usr/bin/rig
