#!/bin/bash

alias ssb="source $HOME/.bashrc"

# sudo
alias sudo=/usr/bin/doas

# power
alias reboot="/usr/bin/doas /usr/bin/reboot"
alias poweroff="/usr/bin/doas /usr/bin/poweroff"

# xdg-mime
alias xxqf="/usr/bin/xdg-mime query filetype"
alias xxqd="/usr/bin/xdg-mime query default"
alias xxd="/usr/bin/xdg-mime default"
alias xx="/usr/bin/xdg-open"
alias umd="/usr/bin/update-mime-database"

# desktop entries
alias dfv="/usr/bin/desktop-file-validate"
alias dfi="/usr/bin/desktop-file-install"
alias udd="/usr/bin/update-desktop-database"

# xdg-dirs
alias udu="/usr/bin/xdg-user-dirs-update"

# xrdb
alias xxx="/usr/bin/xrdb $XDG_CONFIG_HOME/X11/xresources"

# pacman
alias syu="/usr/bin/doas /usr/bin/pacman -Syu"
alias pis="/usr/bin/doas /usr/bin/pacman -S"
alias rns="/usr/bin/doas /usr/bin/pacman -Rns"
alias pss="/usr/bin/pacman -Ss"
alias psi="/usr/bin/pacman -Si"
alias pqs="/usr/bin/pacman -Qs"
alias pqe="/usr/bin/pacman -Qe"
alias pqi="/usr/bin/pacman -Qi"
alias Syu="/usr/bin/yay -Syu"
alias yss="/usr/bin/yay -Ss"
alias ysi="/usr/bin/yay -Si"
alias yqs="/usr/bin/yay -Qs"
alias yqe="/usr/bin/yay -Qe"
alias yqi="/usr/bin/yay -Qi"
alias yis="/usr/bin/yay -S"
alias cache="/usr/bin/doas /usr/bin/pacman -Sc"

# pip
alias ppi="/usr/bin/pip install"
alias ppu="/usr/bin/pip uninstall"
alias ppl="/usr/bin/pip list"
alias ppc="/usr/bin/pip check"
alias pps="/usr/bin/pip show"

# git
alias status="/usr/bin/git status"
alias add="/usr/bin/git add"
alias remove="/usr/bin/git rm"
alias commit="/usr/bin/git commit -m"
alias push="/usr/bin/git push"
alias clone="/usr/bin/git clone"

# himalaya mail client
alias mail=/usr/bin/himalaya
alias sentm="/usr/bin/himalaya -f '[Gmail]/Sent Mail'"
alias spamm="/usr/bin/himalaya -f '[Gmail]/Spam'"
alias draftm="/usr/bin/himalaya -f '[Gmail]/Drafts'"

# navigation
alias ..="cd ..;/usr/bin/clear;/usr/bin/exa -lh --group-directories-first" 
alias ...="cd ../..;/usr/bin/clear;/usr/bin/exa -lh --group-directories-first"
alias ..3="cd ../../..;/usr/bin/clear;/usr/bin/exa -lh --group-directories-first"
alias ..4="cd ../../../..;/usr/bin/clear;/usr/bin/exa -lh --group-directories-first"
alias ..5="cd ../../../../..;/usr/bin/clear;/usr/bin/exa -lh --group-directories-first"

# cd
fcd() {
cd "$(/usr/bin/find $HOME -type d | /usr/bin/fzf)";/usr/bin/clear;/usr/bin/exa -lh --group-directories-first
}
cdd() {
cd "$(/usr/bin/find . -type d | /usr/bin/fzf)";/usr/bin/clear;/usr/bin/exa -lh --group-directories-first
}

# find
alias fff="/usr/bin/find $HOME . > /dev/null"

# grep
alias gpp="/usr/bin/grep -iIrn --color"
alias gss="/usr/bin/find $XDG_CONFIG_HOME/shell -type f | /usr/bin/xargs /usr/bin/grep -iIn --color"
alias wss="/usr/bin/find $XDG_CONFIG_HOME/w3m -type f | /usr/bin/xargs /usr/bin/grep -iIn --color"
alias gbb="/usr/bin/find $HOME/.local/bin -type f | /usr/bin/xargs /usr/bin/grep -iIn --color"
alias gsss="/usr/bin/find $HOME/gits/suckless -type f | /usr/bin/xargs /usr/bin/grep -iIn --color"

# clear
alias cl=/usr/bin/clear
alias clc="/usr/bin/clear;cd"
alias cll="/usr/bin/clear;/usr/bin/exa -lh --group-directories-first"

# bulk rename
alias nn="/usr/local/bin/vimv"

# confirm before overwriting something
alias cp="/usr/bin/cp -vi"
alias mv="/usr/bin/mv -vi"
alias rm="/usr/bin/rm -vI"
alias mkd="/usr/bin/mkdir -vp"

# chown
alias tt=/usr/bin/touch
alias modx="/usr/bin/chmod +x"
alias modu="/usr/bin/chmod -x"
alias own="/usr/bin/doas /usr/bin/chown $(/usr/bin/echo $(/usr/bin/id -un):$(/usr/bin/id -gn))"

# ls
alias ls="/usr/bin/exa -lh --group-directories-first"
alias lsa="/usr/bin/exa -alh --group-directories-first"

# rust alternatives
alias cat=/usr/bin/bat
alias rg="/usr/bin/rg -i --colors 'match:fg:green'"
alias fd="/usr/bin/fd -c always"

# make
alias mmi="/usr/bin/doas /usr/bin/make clean install"
alias mmu="/usr/bin/doas /usr/bin/make clean uninstall"

# trash
alias rmp="/usr/bin/trash put"
alias rml="/usr/bin/trash list"
alias rme="/usr/bin/trash empty"
alias rmt="/usr/bin/trash restore"

# nsxiv
alias iv="/usr/local/bin/nsxiv -ftaoq * | /usr/bin/sed 's@^@'"$PWD"'\/@' | /usr/bin/paste -s -d ' ' | /usr/bin/tr -d '\n' | /usr/bin/xclip -selection clipboard"
alias ivp="/usr/local/bin/nsxiv -ftpaoq * | /usr/bin/sed 's@^@'"$PWD"'\/@' | /usr/bin/paste -s -d ' ' | /usr/bin/tr -d '\n' | /usr/bin/xclip -selection clipboard"

# newsboat
alias nnn="/usr/bin/newsboat -x reload"

# mpv
alias mmm="/usr/bin/mpv *.mp4 *.mkv"
alias mm="/usr/bin/mpv"

# thumbnailer
alias txx="/usr/bin/vcs -i 1m -c 4"

# nvim
alias vi="/usr/bin/nvim -i NONE"
alias vim="/usr/bin/nvim -i NONE"
alias svim=/usr/bin/doasedit
alias vdiff="/usr/bin/nvim -d"
alias vimdiff="/usr/bin/nvim -d"

# whereis
alias ww=/usr/bin/whereis

# ping
alias ping="/usr/bin/ping 8.8.8.8 -c 5"

# space
alias du=/usr/bin/dua
alias df="/usr/bin/df -h"
alias ndu=/usr/bin/ncdu
alias dust="/usr/bin/dust -sp -d 1"
alias free="/usr/bin/free -h -s 2 -c 5"

# youtube-dl
alias yt="/usr/bin/yt-dlp -ic"
alias yta="/usr/bin/yt-dlp -xic"
alias qq="/usr/bin/torsocks /usr/bin/yt-dlp -ic"

# torrent
alias torr=/usr/bin/attractorr

# curl
alias ccc="/usr/bin/curl --remote-name"

# wget
alias wget="/usr/bin/wget --hsts-file=$XDG_DATA_HOME/wget-hsts"

# weather
alias wttr="/usr/bin/curl wttr.in/$place"

# wiki
alias wiki="/usr/bin/wiki-search" # search Arch-Wiki
alias wikk="/usr/bin/wikicurses" # search Wikipedia

# surfraw
alias sr="/usr/bin/sr duckduckgo"

# w3m
alias www="/usr/bin/w3m -config $XDG_CONFIG_HOME/w3m/config"

# checkupdates
alias cu=/usr/bin/checkupdates
alias cn="/usr/bin/checkupdates | /usr/bin/wc -l"

# spreadsheet calculator-improved
alias sc=/usr/bin/sc-im

# neofetch
alias fetch="$HOME/.local/bin/paleofetch"

# assistant
alias sss=/usr/local/bin/oi

# mocp
alias moc="/usr/bin/mocp -M $XDG_CONFIG_HOME/moc"

# autopaper
alias paper="cd $XDG_DOWNLOAD_DIR/autopaper && /usr/bin/python3 $HOME/.local/bin/autopaper"

# cron
alias cronl="/usr/bin/crontab -l"
alias crone="/usr/bin/crontab -e"
alias cronc="/usr/bin/cp /var/spool/cron/ts -t $XDG_CONFIG_HOME/crond/"

# mounting & unmounting
alias bbm="/usr/bin/doas /usr/bin/mount /dev/sdb1 /mnt/usb1 && cd /mnt/usb1 && /usr/bin/exa -alh --group-directories-first"
alias ccm="/usr/bin/doas /usr/bin/mount /dev/sdc1 /mnt/usb2 && cd /mnt/usb2 && /usr/bin/exa -alh --group-directories-first"
alias ddm="/usr/bin/doas /usr/bin/mount /dev/sdd1 /mnt/usb3 && cd /mnt/usb3 && /usr/bin/exa -alh --group-directories-first"
alias bbu="/usr/bin/doas /usr/bin/umount /dev/sdb1"
alias ccu="/usr/bin/doas /usr/bin/umount /dev/sdc1"
alias ddu="/usr/bin/doas /usr/bin/umount /dev/sdd1"

# simple-mtpfs
alias mtll="/usr/bin/simple-mtpfs -l"
alias mtmm="/usr/bin/simple-mtpfs --device 1 $XDG_DOWNLOAD_DIR/mtp"
alias mtuu="/usr/bin/fusermount -uz $XDG_DOWNLOAD_DIR/mtp"

# when & task
alias wwww="/usr/bin/when i"
alias wwwe="/usr/bin/when e"
alias ttt=/usr/bin/task
alias tte="/usr/bin/task add"

# studyflash
alias sffn="/usr/bin/studyflash new"
alias sffa="/usr/bin/studyflash add"
alias sffe="/usr/bin/studyflash edit"
alias sffs="/usr/bin/studyflash study"

# formatting
alias fat="/usr/bin/mkfs.vfat -F 32 /dev/sd" # additionally specify, -i VOLUME_ID
alias ext="/usr/bin/mkfs.ext4 /dev/sd" # additionally specify, -L volume_label
