#!/bin/bash

# set tty console font
setfont ter-120b

# turn off annoying beep
set bell-style none

# set vi mode
set -o vi

# autocd
#shopt -s autocd

# prevent overwrite of files
#set -o noclobber

# defaults
export PAGER=/usr/bin/less
export VISUAL=/usr/bin/nvim
export EDITOR=/usr/bin/nvim
export SUDO_EDITOR=/usr/bin/nvim
export READER=/usr/bin/zathura
export TERMINAL=/usr/local/bin/st
export COLORTERM="st-256color"
export BROWSER=/usr/bin/librewolf
export BROWSERCLI=/usr/bin/lynx
export VIDEO=/usr/bin/mpv
export IMAGE=/usr/local/bin/nsxiv
export WM=/usr/local/bin/dwm

# keep history file
set -o history

# clear history on exit
unset HISTFILE

# append to history
shopt -s histappend

# ignore these commands
export HISTIGNORE="man:cat:less:vi:pss:psi:yss:ysi:cl:cll:clc:fcd:cdd:op:opp:xx:df:du:brtt:batt:mute:vol:vol70:sr:iv:mm:torr:wttr:cu:cn:yt:yta:qq"

# ignore duplicates
export HISTCONTROL="ignoredups:erasedups"

# xdg-usr-directories
export XDG_DOWNLOAD_DIR=$HOME/dl
export XDG_DOCUMENTS_DIR=$HOME/dox
export XDG_MUSIC_DIR=$HOME/musix
export XDG_PICTURES_DIR=$HOME/pix
export XDG_VIDEOS_DIR=$HOME/vids
export XDG_DESKTOP_DIR=$HOME/
export XDG_TEMPLATES_DIR=$HOME/
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_DIRS="/usr/local/share:/usr/share:$HOME/.local/share"
export XDG_CONFIG_DIRS=/etc/xdg
export XDG_RUNTIME_DIR=/run/user/$UID

# xdg-ninja
export XAUTHORITY=/tmp/Xauthority
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export GOPATH="$XDG_DATA_HOME"/go
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export CALCHISTFILE="$XDG_CACHE_HOME"/calc_history
export HISTFILE="${XDG_STATE_HOME}"/bash/history
export LESSHISTFILE="$XDG_DATA_HOME"/lesshst
export W3M_DIR="$XDG_CONFIG_HOME"/w3m
export ANTIWORDHOME="$XDG_DOWNLOAD_DIR"/antiword

# R
export R_HOME_USER="$XDG_CONFIG_HOME/R"
export R_PROFILE_USER="$XDG_CONFIG_HOME/R/profile"
export R_HISTFILE="$XDG_CONFIG_HOME/R/history"
export R_LIBS_USER="$XDG_DATA_HOME/R"

# add custom folder to Path
export PATH="${PATH}:$HOME/.local/bin"

# fzf defaults
export FZF_DEFAULT_OPTS="--cycle --height 10%"

# sk defaults
export SKIM_DEFAULT_OPTIONS="--multi --height 10%"

# define Home for any web browser
export WWW_HOME="https://duckduckgo.com"
