#!/bin/sh

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
/usr/bin/touch /tmp/Xauthority
/usr/bin/xset r rate 300 50 &
/usr/bin/xrdb -load $XDG_CONFIG_HOME/X11/xresources &
/usr/bin/unclutter &
/usr/local/bin/slstatus > /dev/null 2>&1 &
$HOME/.local/bin/xinfo &
$XDG_CONFIG_HOME/xwallpaper/swall &
exec /usr/local/bin/st &

exec /usr/local/bin/dwm > /dev/null 2>&1
