#!/bin/sh

/usr/bin/xset +fp /usr/local/share/fonts/
/usr/bin/xrdb -load $XDG_CONFIG_HOME/X11/xresources
/usr/bin/xset r rate 300 50 &
/usr/bin/unclutter &
/usr/local/bin/slstatus >/dev/null 2>&1 &
$HOME/.local/bin/swall &
exec /usr/local/bin/st &

exec /usr/local/bin/dwm > /dev/null 2>&1
