#!/bin/sh

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
/usr/bin/touch /tmp/Xauthority
/usr/bin/xrdb -load $XDG_CONFIG_HOME/X11/xresources &
$HOME/.local/bin/bright &
/usr/bin/xset r rate 200 50 &
#/usr/bin/xset r off &
/usr/bin/unclutter &
/usr/bin/picom > /dev/null 2>&1 &
/usr/local/bin/dwmblocks > /dev/null 2>&1 &
$HOME/.local/bin/xinfo &
$XDG_CONFIG_HOME/xwallpaper/swall &
exec /usr/local/bin/st &

exec /usr/local/bin/dwm > /dev/null 2>&1
