#
# .bash_aliases
#

alias ssb="source $HOME/.bashrc"

# sudo
alias sudo=/usr/bin/doas

# power
alias reboot="/usr/bin/doas /usr/bin/reboot"
alias poweroff="/usr/bin/doas /usr/bin/poweroff"

# hardware
alias batt="/usr/bin/grep -E 'STATUS|CAPACITY' /sys/class/power_supply/BAT0/uevent | /usr/bin/sed 's/^.*\=//g;2q'"
alias brtt="/usr/bin/cat /sys/class/backlight/nv_backlight/brightness"
alias sound="/usr/bin/amixer sget Master | grep Mono\: | awk '{print \$4 \$6}'"

# xdg-mime
alias xxqf="/usr/bin/xdg-mime query filetype"
alias xxqd="/usr/bin/xdg-mime query default"
alias xxd="/usr/bin/xdg-mime default"
alias xx="/usr/bin/xdg-open"

# amixer
alias mute="/usr/bin/amixer -q sset Master toggle"
alias vol="/usr/bin/amixer -q set Master 100\% unmute"
alias vol60="/usr/bin/amixer -q set Master 60\% unmute"
alias up="/usr/bin/amixer -q set Master 5\%\+ unmute"
alias down="/usr/bin/amixer -q set Master 5\%\- unmute"

# pacman
alias syu="/usr/bin/doas /usr/bin/pacman -Syu"
alias pis="/usr/bin/doas /usr/bin/pacman -S"
alias rns="/usr/bin/doas /usr/bin/pacman -Rns"
alias pss="/usr/bin/pacman -Ss"
alias psi="/usr/bin/pacman -Si"
alias pqs="/usr/bin/pacman -Qs"
alias pqe="/usr/bin/pacman -Qe"
alias pqi="/usr/bin/pacman -Qi"
alias Syu="/usr/bin/yay -Syu"
alias yss="/usr/bin/yay -Ss"
alias ysi="/usr/bin/yay -Si"
alias yqs="/usr/bin/yay -Qs"
alias yqe="/usr/bin/yay -Qe"
alias yqi="/usr/bin/yay -Qi"
alias yis="/usr/bin/yay -S"
alias cache="/usr/bin/doas /usr/bin/pacman -Sc"

# pip
alias ppi="/usr/bin/pip install"
alias ppu="/usr/bin/pip uninstall"
alias ppl="/usr/bin/pip list"
alias ppc="/usr/bin/pip check"
alias pps="/usr/bin/pip show"

# git
alias gs="/usr/bin/git status"
alias ga="/usr/bin/git add"
alias gc="/usr/bin/git commit -m"
alias gp="/usr/bin/git push"

# himalaya mail client
alias mail=/usr/bin/himalaya
alias sent="/usr/bin/himalaya -m '[Gmail]/Sent Mail'"
alias spam="/usr/bin/himalaya -m '[Gmail]/Spam'"
alias drafts="/usr/bin/himalaya -m '[Gmail]/Drafts'"

# navigation
alias ..="cd ..;/usr/bin/clear;/usr/bin/exa -lh --group-directories-first" 
alias ...="cd ../..;/usr/bin/clear;/usr/bin/exa -lh --group-directories-first"
alias ..3="cd ../../..;/usr/bin/clear;/usr/bin/exa -lh --group-directories-first"
alias ..4="cd ../../../..;/usr/bin/clear;/usr/bin/exa -lh --group-directories-first"
alias ..5="cd ../../../../..;/usr/bin/clear;/usr/bin/exa -lh --group-directories-first"

# fzf
fcd() {
	cd "$(/usr/bin/find $HOME -type d | fzf)";/usr/bin/clear;/usr/bin/exa -lh --group-directories-first
}
op() {
	/usr/bin/xdg-open "$(/usr/bin/find $HOME -type f | fzf)"
}
alias path="/usr/bin/find $HOME -type f | fzf | /usr/bin/sed 's/\.\//\$HOME\//' | /usr/bin/tr -d '\n' | /usr/bin/xclip -selection c"
alias rpath="/usr/bin/find /usr | fzf"
alias gss="/usr/bin/git ls-files -m -o --exclude-standard | fzf -m --print0 | /usr/bin/xargs -0 -o -t /usr/bin/git add -p"

# clear
alias cl=/usr/bin/clear
alias clc="/usr/bin/clear;cd"
alias cll="/usr/bin/clear;/usr/bin/exa -lh --group-directories-first"

# rename
alias nn="/usr/local/bin/vimv"

# confirm before overwriting something
alias cp="/usr/bin/cp -vi"
alias mv="/usr/bin/mv -vi"
alias rm="/usr/bin/rm -vI"
alias mkd="/usr/bin/mkdir -vp"

# ls
alias ls="/usr/bin/exa -lh --group-directories-first"
alias lsa="/usr/bin/exa -alh --group-directories-first"

# rust alternatives
alias cat=/usr/bin/bat
alias rg="/usr/bin/rg -i --colors 'match:fg:green'"
alias fd="/usr/bin/fd -c always"

# make
alias mmi="/usr/bin/doas /usr/bin/make clean install"
alias mmu="/usr/bin/doas /usr/bin/make clean uninstall"

# trash
alias rmp="/usr/bin/trash put"
alias rml="/usr/bin/trash list"
alias rme="/usr/bin/trash empty"
alias rmt="/usr/bin/trash restore"

# nsxiv
alias iv="/usr/local/bin/nsxiv -ftraq *"
alias ivv="/usr/local/bin/nsxiv -ftpraq *"

# nvim
alias vi=/usr/bin/nvim
alias vim=/usr/bin/nvim
alias svim="/usr/bin/doas /usr/bin/nvim"
alias vimdiff="/usr/bin/nvim -d"

# ping
alias pp="/usr/bin/ping 8.8.8.8 -c 5"

# space
alias df=/usr/bin/ncdu
alias du=/usr/bin/dust
alias free="/usr/bin/free -h -s 2 -c 5"

# youtube-dl
alias yt="/usr/bin/yt-dlp --add-metadata -ic"
alias yta="/usr/bin/yt-dlp --add-metadata -xic"
alias qq="/usr/bin/torsocks /usr/bin/yt-dlp --add-metadata -ic"

# torrent
alias torr=/usr/bin/attractorr

# subtitles
alias sub="$HOME/.local/bin/opensubtitles-dl.sh -l eng -n"

# curl
alias cc="/usr/bin/curl --remote-name"

# weather
alias wttr="/usr/bin/curl wttr.in/$place"

# wiki
alias wiki="/usr/bin/wiki-search" # search Arch-Wiki
alias wikk="/usr/bin/wikicurses" # search Wikipedia

# surfraw
alias sr="/usr/bin/sr duckduckgo"

# checkupdates
alias cu=/usr/bin/checkupdates
alias cn="/usr/bin/checkupdates | /usr/bin/wc -l"
